plugins:
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  es6: true
  node: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

rules:
  no-console: 0
  semi: 0